'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    await queryInterface.bulkInsert('Videos', [
      {
        id: 1,
        title: "Setup react native on Mac",
        video: "WAGMEypfHTI",
        courseContentID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        title: "Setup react native on Linux",
        video: "9TqadLa-KEs&t",
        courseContentID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        title: "Setup react native on Windows",
        video: "Slr850MSz6w",
        courseContentID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        title: "Tìm hiểu về Components",
        video: "Mhdl-qppnlY&t",
        courseContentID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        title: "Class và function component",
        video: "K16eNEdRuko&t",
        courseContentID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        title: "Props và state",
        video: "Z0DK42bwWzs",
        courseContentID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        title: "View, StyleSheet và Text Image",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        title: "TextInput và ScrollView",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        title: "FlatList và SectionList",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        title: "Sử dụng Modal và Alert",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        title: "Dimensions, Linking",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        title: "Tạo chuyển động với Animated",
        video: "Z0DK42bwWzs",
        courseContentID: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        title: "Tìm hiểu về react native",
        video: "Z0DK42bwWzs",
        courseContentID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        title: "react native navigation là gì?",
        video: "Z0DK42bwWzs",
        courseContentID: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        title: "Cài đặt react native navigation",
        video: "Z0DK42bwWzs",
        courseContentID: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        title: "Stack và truyền Param",
        video: "Z0DK42bwWzs",
        courseContentID: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        title: "Tab",
        video: "Z0DK42bwWzs",
        courseContentID: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        title: "Drawer",
        video: "Z0DK42bwWzs",
        courseContentID: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        title: "Vòng đời của component",
        video: "Z0DK42bwWzs",
        courseContentID: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        title: "React native hook",
        video: "Z0DK42bwWzs",
        courseContentID: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        title: "Dự án thực tế P1",
        video: "Z0DK42bwWzs",
        courseContentID: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        title: "Dự án thực tế P2",
        video: "Z0DK42bwWzs",
        courseContentID: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        title: "Dự án thực tế P3",
        video: "Z0DK42bwWzs",
        courseContentID: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        title: "Dự án thực tế P4",
        video: "Z0DK42bwWzs",
        courseContentID: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        title: "Redux",
        video: "Z0DK42bwWzs",
        courseContentID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});

  },

  down: async (queryInterface, Sequelize) => {

    await queryInterface.bulkDelete('Videos', null, {});

  }
};
